#!/usr/bin/python
#
# Check for insecure content in https webpage
# sys.argv[1] == url to be checked
#
# TODO: prototypes are clunky
#
# requires deb python-selenium
# non-dpkg install of phantomjs: npm install phantomjs-prebuilt


import os
import sys
import signal

from selenium import webdriver

try:
    url = sys.argv[1]
except IndexError:
    print "No hostname specified, try https://google.com as arg[1]?"
    sys.exit(3)

#driver = webdriver.PhantomJS()
driver = webdriver.PhantomJS(service_log_path=os.path.devnull)
driver.set_window_size(1120, 550)

driver.get(url)

print driver.current_url,

browser_log = driver.get_log("browser")

# http://stackoverflow.com/questions/25110624/how-to-properly-stop-phantomjs-execution
driver.service.process.send_signal(signal.SIGTERM)
driver.quit()

insecureflag = False

if browser_log:
    for entry in browser_log:
        for key,value in entry.items():
            if key == "message":
                print value.replace("\n (:)", ""),
                if u'insecure' in value:
                    insecureflag = True

    if insecureflag:
        print "Browser log matches /insecure/. Alarm."
        sys.exit(2)

    else:
        print "Something going on, but not insecure"
        sys.exit(1)

else:
    print "No logs from webdriver.PhantomJS()"
    sys.exit(0)

