#!/bin/bash

set -euo pipefail

IMAGE=check-http-insecure-content
NAME=${IMAGE}-${RANDOM}
NS=nagios
KUBECTL="/usr/local/bin/kubectl --namespace $NS"

$KUBECTL run $NAME \
  --quiet \
  --image-pull-policy Always \
  --image eu.gcr.io/divine-arcade-95810/$NAME:latest \
  --restart Never \
  --rm \
  -it \
  --env="URL=$1"

$KUBECTL get pods --show-all --selector name=$NAME -o name 2>/dev/null \
  | while read POD ; do kubectl delete $POD; done >/dev/null 2>/dev/null

